const crypto = require('crypto');
const PRODUCT = 'HRPRO-JORDAN';
// Replace this public key with the production public key generated by the vendor.
// The private signing key must NEVER be shipped inside the application.
const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzDirkkNKaVJ0ITq92saV
7SO47w7HKJDXmY5u9ZsbDTs4rP9uEKEBrVLiMOICTaG6axeHmRiAtDaE5keE8y/2
jsGI8GZjYIWI/4RhFqR2EwVIwxVyxUS1psXjhljdXWNdiFBX0tn0HxkJ5nz1zaE/
oND5Kf1g2mFbdspWD97b+KGL+DMBOoyR8Eva/5r5xkaXkxW8a+sOQe1pIJ1oZmGu
4iVKmBIFHigWhI4uIZsYAC4SIdYHhi3l57aoV8RoLaAlUIGDtMHnQ/C8qCgzCwj8
x2tSVZo5DMcnJHaKv5C38IC5H/HlvbSsLxsQkeiBRFeHz6JXM8sS9DDgRnQDNdld
TwIDAQAB
-----END PUBLIC KEY-----`;

function normalizeKey(key) { return String(key || '').trim().toUpperCase().replace(/\s+/g, ''); }
function fingerprint(payload) { return crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex').slice(0, 16).toUpperCase(); }
function canonicalPayload(license) {
  return JSON.stringify({ product: license.product, plan: license.plan || 'STANDARD', expiresAt: license.expiresAt || null, maxEmployees: license.maxEmployees ?? null, companyId: license.companyId || null });
}
function verifyLicense(license) {
  if (!license || typeof license !== 'object') return { ok: false, reason: 'LICENSE_MISSING' };
  if (license.product !== PRODUCT) return { ok: false, reason: 'PRODUCT_MISMATCH' };
  if (!license.signature || !PUBLIC_KEY_PEM) return { ok: false, reason: 'LICENSE_SIGNATURE_REQUIRED' };
  try {
    const verify = crypto.createVerify('SHA256');
    verify.update(canonicalPayload(license)); verify.end();
    if (!verify.verify(PUBLIC_KEY_PEM, Buffer.from(license.signature, 'base64'))) return { ok: false, reason: 'INVALID_SIGNATURE' };
  } catch { return { ok: false, reason: 'SIGNATURE_ERROR' }; }
  if (license.expiresAt) {
    const expiry = new Date(license.expiresAt);
    if (!Number.isFinite(expiry.getTime())) return { ok: false, reason: 'INVALID_EXPIRY' };
    if (expiry.getTime() < Date.now()) return { ok: false, reason: 'LICENSE_EXPIRED' };
  }
  return { ok: true, product: PRODUCT, plan: license.plan || 'STANDARD', expiresAt: license.expiresAt || null, maxEmployees: license.maxEmployees ?? null, companyId: license.companyId || null };
}
module.exports = { verifyLicense, normalizeKey, fingerprint, canonicalPayload, PUBLIC_KEY_PEM };
